# Generated by Django 4.1.7 on 2023-03-16 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyecto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcercaDeMi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=60)),
                ('autor', models.CharField(max_length=60)),
                ('editorial', models.CharField(max_length=60)),
                ('genero', models.CharField(max_length=60)),
                ('precio', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=60)),
                ('autor', models.CharField(max_length=60)),
                ('editorial', models.CharField(max_length=60)),
                ('genero', models.CharField(max_length=60)),
                ('precio', models.CharField(max_length=60)),
            ],
        ),
        migrations.DeleteModel(
            name='Clientes',
        ),
        migrations.DeleteModel(
            name='Generos',
        ),
        migrations.DeleteModel(
            name='Libros',
        ),
    ]
