# Generated by Django 4.1.7 on 2023-03-20 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyecto', '0002_acercademi_compra_venta_delete_clientes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='editorial',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='editorial',
        ),
    ]
