# Generated by Django 4.1.7 on 2023-03-27 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyecto', '0007_catalogo_delete_acercademi_delete_compra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='libros'),
        ),
    ]
