# Generated by Django 4.1.7 on 2023-03-31 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyecto', '0010_alter_comentarios_comentario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentarios',
            name='vendedor',
        ),
        migrations.AddField(
            model_name='comentarios',
            name='nombre',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
